name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACPA_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.ACPA_SSH_KNOWN_HOSTS }}

      - name: Creating .env file
        run: |
          touch .env
          echo ACPA_STRIPE_SK=${{ secrets.ACPA_STRIPE_SK }} >> .env
          echo ACPA_STRIPE_WEBHOOK_SECRET=${{ secrets.ACPA_STRIPE_WEBHOOK_SECRET }} >> .env
          echo BASE_URL=${{ secrets.ACPA_REACT_APP_FRONTEND_SERVER }} >> .env
          echo ACPA_EXPO_ACCESS_TOKEN=${{ secrets.ACPA_EXPO_ACCESS_TOKEN }} >> .env
          echo REFERRAL_POINT_EARNED=1 >> .env
          echo BRONZE_POINTS=5 >> .env
          echo SILVER_POINTS=10 >> .env
          echo GOLD_POINTS=15 >> .env
          echo NODE_ENV=production >> .env
          cat .env

      - name: Build and deploy
        run: ./deploy-prod.sh
